version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - cd ./index-photos
      - zip -r function.zip ./*
      - aws s3 cp function.zip s3://bucketp-pipeline/function.zip


  post_build:
    commands:
     - aws lambda update-function-code function-name index-photos --s3-bucket bucketp-pipeline --s3-key function.zip --publish

      #- aws lambda update-function-code --function-name index-photos --zip-file fileb://deployment_package.zip
      #- aws lambda update-function-code --function-name index-photos --zip-file https://bucketp-pipeline.s3.amazonaws.com/function.zip

#      - chmod +x deploy-lambda.sh
#      - ./deploy-lambda.sh
artifacts:
  type: zip
  files:
    - function.zip
#    - template.yaml
#    - outputsamtemplate.yml
    
