version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - cd ./index-photos
      - zip -r function.zip ./*
      - aws s3 cp function.zip s3://bucketp-pipeline/function.zip

      - cd ./search-photos
      - zip -r function1.zip ./*
      - aws s3 cp function1.zip s3://bucketp-pipeline/function1.zip


  post_build:
    commands:
     - aws lambda update-function-code --function-name index-photos --s3-bucket bucketp-pipeline --s3-key function.zip --publish
     - aws lambda update-function-code --function-name search-photos --s3-bucket bucketp-pipeline --s3-key function1.zip --publish



artifacts:
  type: zip
  files:
    - '**/*'


