version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket bucketp-pipeline --output-template-file outputsamtemplate.yml
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://deployment.zip
#      - chmod +x deploy-lambda.sh
#      - ./deploy-lambda.sh
artifacts:
  type: zip
  files:
    - template.yaml
    - outputsamtemplate.yml
    
